server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ural-aggregator
    version: @project.version@

security:
  jwt:
    public-key: ${PUBLIC_KEY}

proxy:
  auth:
    url: ${PROXY_AUTH_URL}
  users:
    url: ${PROXY_USERS_URL}
  cars:
    url: ${PROXY_CARS_URL}
  cargo:
    url: ${PROXY_CARGO_URL}
  contracts:
    url: ${PROXY_CONTRACTS_URL}

front:
  url: ${FRONT_URL}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
