server:
  port: 10902

spring:
  application:
    name: ural-aggregator
    version: @project.version@

security:
  jwt:
    public-key: ${PUBLIC_KEY}

proxy:
  cargo:
    url: http://localhost:10903
  users:
    url: http://localhost:10904
  auth:
    url: http://localhost:10901

logging:
  level:
    root: info
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
